/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.scalecap;

import com.scalecap.domain.HttpService;
import com.scalecap.domain.WebCrawlerService;

import java.util.Map;
import java.util.Scanner;

public class App {

    public static void main(String[] args) {

        System.out.print("Enter search term: ");
        Scanner scanner = new Scanner(System.in);
        String searchTerm = scanner.next();

        WebCrawlerCommand webCrawlerCommand = bootStrap();
        Map<String, Long> topFiveJsLibs = webCrawlerCommand.findMostUsedJsLibraries(searchTerm, 5);

        System.out.printf("%-30.30s %-30.30s", "Library", "Count");
        System.out.println();
        topFiveJsLibs.forEach((libraryName, count) -> {
            System.out.printf("%-30.30s %-30.30s", libraryName, count);
            System.out.println();
        });

    }

    static WebCrawlerCommand bootStrap() {
        HttpService httpService = new WebHttpService();
        WebCrawlerService webCrawlerService = new WebCrawlerService(new WebSearchService(httpService, new Config()), httpService);
        return new WebCrawlerCommand(webCrawlerService);
    }
}
